# SPDX-License-Identifier: GPL-3.0-only
from __future__ import annotations

import json
import os
from pathlib import Path
import shutil

from .assembly_policy import AssemblyError

REQUIRED_WEBUI_FILES = {"index.html", "style.css", "app.js", "runtime-config.js"}
ALLOWED_WEBUI_SUFFIXES = {".html", ".css", ".js"}


def _iter_regular_files(root: Path, *, suffixes: set[str]) -> list[Path]:
    files: list[Path] = []
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise AssemblyError(f"WebUI source contains a symbolic link: {path}")
        if path.is_dir():
            continue
        if not path.is_file():
            raise AssemblyError(f"WebUI source contains an unsupported entry: {path}")
        if path.suffix.lower() not in suffixes:
            raise AssemblyError(f"WebUI source contains an unsupported file type: {path}")
        files.append(path)
    return files


def _runtime_config(module_id: str) -> bytes:
    encoded = json.dumps(module_id, ensure_ascii=True)
    return (
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "// Generated by the validation-module assembler.\n"
        f"export const MODULE_ID = {encoded};\n"
        'export const STATUS_BRIDGE = "scripts/webui/status.sh";\n'
    ).encode("utf-8")


def copy_webui_assets(source_root: Path, staging: Path, module_id: str) -> dict[str, object]:
    webui_source = source_root / "src/webui"
    bridge_source = source_root / "scripts/webui"
    webui_exists = webui_source.exists()
    bridge_exists = bridge_source.exists()

    if not webui_exists and not bridge_exists:
        return {"included": False, "file_count": 0}
    if not webui_exists or not bridge_exists:
        raise AssemblyError("WebUI source and status-bridge source must be present together")
    if not webui_source.is_dir() or webui_source.is_symlink():
        raise AssemblyError("src/webui must be a real directory")
    if not bridge_source.is_dir() or bridge_source.is_symlink():
        raise AssemblyError("scripts/webui must be a real directory")

    webui_files = _iter_regular_files(webui_source, suffixes=ALLOWED_WEBUI_SUFFIXES)
    relative_names = {path.relative_to(webui_source).as_posix() for path in webui_files}
    missing = sorted(REQUIRED_WEBUI_FILES - relative_names)
    if missing:
        raise AssemblyError(f"required WebUI files are missing: {missing}")

    bridge_files = _iter_regular_files(bridge_source, suffixes={".sh"})
    if {path.relative_to(bridge_source).as_posix() for path in bridge_files} != {"status.sh"}:
        raise AssemblyError("scripts/webui must contain exactly status.sh")

    destination = staging / "webroot"
    destination.mkdir(parents=True, exist_ok=True)
    for source in webui_files:
        relative = source.relative_to(webui_source)
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        os.chmod(target, 0o644)

    runtime_config = destination / "runtime-config.js"
    runtime_config.write_bytes(_runtime_config(module_id))
    os.chmod(runtime_config, 0o644)

    bridge_destination = staging / "scripts/webui"
    bridge_destination.mkdir(parents=True, exist_ok=True)
    for source in bridge_files:
        target = bridge_destination / source.name
        shutil.copyfile(source, target)
        os.chmod(target, 0o755)

    return {
        "included": True,
        "file_count": len(webui_files) + len(bridge_files),
        "module_id": module_id,
    }
