plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.zhanfg.galleryguard'
    compileSdk 37

    defaultConfig {
        applicationId "io.github.zhanfg.galleryguard"
        minSdk 26
        targetSdk 37
        versionCode 14001
        versionName "1.4.0-alpha1"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    packaging {
        resources {
            merges += "META-INF/xposed/*"
        }
    }

    lint {
        checkReleaseBuilds false
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation 'io.github.libxposed:service:102.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
}
